import { h } from '../lib/h.mjs';

const fallback = 'assets/common/amiya.png';
const groups = (title, commands) => h('div', { style: { display: 'flex', flexDirection: 'column' } }, h('div', { style: { height: 42, backgroundColor: '#303030', borderBottom: '2px solid #fff', color: '#fff', display: 'flex', alignItems: 'center', paddingLeft: 24, fontSize: 22, fontWeight: 700 } }, title), h('div', { style: { display: 'flex', flexWrap: 'wrap', padding: 10, gap: 12, backgroundColor: '#050505' } }, commands.map((cmd) => h('div', { style: { width: 148, height: 52, border: '1px solid #fff', borderRadius: 10, color: '#fff', display: 'flex', flexDirection: 'column', padding: 8, fontWeight: 700 } }, h('div', { style: { display: 'flex', alignItems: 'center', fontSize: 15 } }, `${cmd.Cmd} ${cmd.Param}`.trim(), cmd.IsBind ? '  ●' : ''), h('div', { style: { display: 'flex', flexDirection: 'column', marginTop: 3, fontSize: 13 } }, cmd.Desc)))));

export default async function render(props, { image }) {
  const [banner, label, bg, amiya] = await Promise.all([image('assets/help/banner.png', fallback), image('assets/help/label.png', fallback), image('assets/help/bg.jpg', fallback), image('assets/help/amiya.png', fallback)]);
  return h('div', { style: { width: 660, minHeight: 1366, display: 'flex', flexDirection: 'column', fontFamily: 'NotoSansHans', backgroundColor: '#050505', backgroundImage: `url(${amiya})`, backgroundSize: '660px auto', backgroundPosition: 'center 250px', backgroundRepeat: 'no-repeat' } }, h('div', { style: { height: 258, display: 'flex', flexDirection: 'column', padding: 22, color: '#fff', backgroundImage: `url(${banner})`, backgroundSize: 'cover' } }, h('div', { style: { display: 'flex', fontSize: 30, fontWeight: 700, marginTop: 105 } }, '使用说明'), h('div', { style: { display: 'flex', fontSize: 18, marginTop: 12 } }, '● 为需要绑定角色的指令')), h('div', { style: { display: 'flex', flexDirection: 'column', backgroundImage: `url(${bg})`, backgroundSize: 'cover' } }, groups('私聊指令', props.PrivateCmds ?? []), groups('普通指令', props.PublicCmds ?? []), groups('管理员指令', props.AdminCmds ?? [])));
}
